version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_TELEGRAM_BOT_TOKEN=7568759273:AAHoUoR9GDxpXr6x6LiOinQqXgbQ09zwsNY
      - NEXT_PUBLIC_TELEGRAM_CHAT_ID=-1002470042907
      - NEXT_PUBLIC_SANITY_PROJECT_ID=5eulp3wj
    restart: always
